repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.79.1
    hooks:
      - id: terraform_fmt
        args:
          - --args=-write=true
      - id: terraform_validate
        args:
          - --args=-no-color
      - id: terraform_tflint
        args:
          - --args=--config='.tflint.hcl'
      - id: terraform_tfsec
        args:
          - --args=--no-color
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
      - id: terraform_checkov
